= Nvim memo
:sectnums:

== lua-guide

* https://neovim.io/doc/user/lua-guide.html

* neovim API

** The "Vim API" inherited from Vim: Ex-commands and builtin-functions as
well as user-functions in Vimscript. These are accessed through `vim.cmd()`
and `vim.fn` respectively.
*** `vim.cmd`: Ex-commands started in command-line by ':'
*** `vim.fn`: Vimscript functions

** The "Nvim API" written in C for use in remote plugins and GUIs; see api.
These functions are accessed through `vim.api`.

** The "Lua API" written in and specifically for Lua. These are any other
functions accessible through `vim.*` not mentioned already; see lua-stdlib.

=== Using lua

You can also use `:lua=`, which is equivalent to `:lua vim.print(...)`, to
conveniently check the value of a variable or a table:

[listing]
----
:lua =package
----

To run a Lua script in an external file, you can use the `:source` command
exactly like for a Vimscript file:

[listing]
----
:source ~/programs/baz/myluafile.lua
----

Finally, you can include Lua code in a Vimscript file by putting it inside a
:lua-heredoc block:

[listing]
----
lua << EOF
  local tbl = {1, 2, 3}
  for k, v in ipairs(tbl) do
    print(v)
  end
EOF
----


루아 모듈들은 네오빔의 `runtimepath` (대부분의 *nix 시스템에서는 `~/.config/nvim/lua`,
윈도우에서는 `~/AppData/Local/nvim/lua`) 안의 `lua/` 폴더에 위치합니다. 이 폴더에 있는
루아 파일들은 모듈로 `require()` 할 수 있습니다


== Variables

[listing]
----
vim.g: global variables (g:)
vim.b: variables for the current buffer (b:)
vim.w: variables for the current window (w:)
vim.t: variables for the current tabpage (t:)
vim.v: predefined Vim variables (v:)
vim.env: environment variables defined in the editor session
----


== Modules

[listing]
----
no-ns: builtin-functions

vim : lua standard library functions and sub modules

----


=== vim module

* Lua "standard library" (stdlib).
* It is always loaded, thus `require("vim")` is unnecessary.

[listing]
----
;; You can peek at the module properties:
:lua vim.print(vim)

;; To find documentation on e.g. the "deepcopy" function:
:help vim.deepcopy()
----


